#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG="/usr/bin/pushbot/pushbot"

start_service() {
	local enabled
	enabled=$(uci -q get pushbot.pushbot.pushbot_enable)
	[ "$enabled" != "1" ] && return 0
	
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	killall -9 pushbot 2>/dev/null
}

reload_service() {
	stop
	start
}
